[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

 [dependencies]
 rand.workspace = true
 rand_core.workspace = true
 getrandom.workspace = true
 rand_chacha.workspace = true
 serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true

[dev-dependencies]